# Generated by Django 4.0.6 on 2025-03-25 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.conjuntoindicadores')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='SerieDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_desagregacion_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('desagregacion_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('periodicidad', models.CharField(blank=True, max_length=255, null=True)),
                ('entidad_recopilatoria', models.CharField(blank=True, max_length=255, null=True)),
                ('fuente_datos', models.CharField(blank=True, max_length=255, null=True)),
                ('desagregacion_tematica', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tematica'),
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_dato', models.DateField()),
                ('valor_dato', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('serie_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.seriedatos')),
            ],
        ),
    ]
